defaults:
  - override /database@_global_: island_small
  - override /evolution@_global_: sgr_small_budget
  - override /task@_global_: sgr_fibonacci
  - override /cluster@_global_: local
  - _self_

variant_suffix: ""
